using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudyPilotApp.Data;
using StudyPilotApp.Models;
using StudyPilotApp.Services;
using StudyPilotApp.ViewModels;

namespace StudyPilotApp.Controllers;

[Authorize(Roles="Faculty")]
public sealed class FacultyResourcesController:Controller
{
    private readonly UserManager<ApplicationUser> _users;private readonly ApplicationDbContext _db;private readonly IFacultyResourceService _service;private readonly IFacultyAssessmentService _courses;private readonly IResourceService _files;
    public FacultyResourcesController(UserManager<ApplicationUser> users,ApplicationDbContext db,IFacultyResourceService service,IFacultyAssessmentService courses,IResourceService files){_users=users;_db=db;_service=service;_courses=courses;_files=files;}
    [HttpGet]public async Task<IActionResult> Index(string? search,int? assignmentId,ResourceCategory? category,FacultyResourceStatus? status,CancellationToken token){var c=await Context(token);if(c is null)return Challenge();search=CleanSearch(search);if(category.HasValue&&!Enum.IsDefined(category.Value))category=null;if(status.HasValue&&!Enum.IsDefined(status.Value))status=null;var courses=await _courses.GetCourseOptionsAsync(c.Value.User.Id,token);if(assignmentId.HasValue&&courses.All(x=>x.AssignmentId!=assignmentId))assignmentId=null;var m=new FacultyResourceIndexViewModel{Search=search,AssignmentId=assignmentId,Category=category,Status=status,Courses=courses,Items=await _service.SearchAsync(c.Value.User.Id,search,assignmentId,category,status,token)};Shell(m,c.Value.User,c.Value.Profile);return View(m);}
    [HttpGet]public async Task<IActionResult> Details(int id,CancellationToken token){var c=await Context(token);if(c is null)return Challenge();var x=await _service.GetOwnedAsync(c.Value.User.Id,id,token:token);if(x is null)return NotFound();var m=new FacultyResourceDetailsViewModel{Resource=x,StudentCount=await _db.StudyResources.CountAsync(r=>r.FacultyResourceId==id,token)};Shell(m,c.Value.User,c.Value.Profile);return View(m);}
    [HttpGet]public async Task<IActionResult> Create(int? assignmentId,CancellationToken token){var c=await Context(token);if(c is null)return Challenge();var m=new FacultyResourceFormViewModel{AssignmentId=assignmentId,Kind=ResourceKind.File,Category=ResourceCategory.Notes};await Prepare(m,c.Value.User.Id,token);Shell(m,c.Value.User,c.Value.Profile);return View(m);}
    [HttpPost,ValidateAntiForgeryToken,RequestSizeLimit(ResourceService.MaximumFileSize+1_048_576)]public async Task<IActionResult> Create(FacultyResourceFormViewModel m,CancellationToken token){var c=await Context(token);if(c is null)return Challenge();await Validate(m,false,null,token);StoredResourceFile? stored=null;if(ModelState.IsValid&&m.Kind==ResourceKind.File)try{await ValidateSignature(m.Upload!,token);if(ModelState.IsValid)stored=await _files.StoreFileAsync(m.Upload!,token);}catch(InvalidOperationException e){ModelState.AddModelError(nameof(m.Upload),e.Message);}if(!ModelState.IsValid){await Prepare(m,c.Value.User.Id,token);Shell(m,c.Value.User,c.Value.Profile);return View(m);}var id=await _service.CreateAsync(c.Value.User.Id,Input(m),stored,token);if(id==0){if(stored is not null)await _files.DeleteStoredFileAsync(stored.StoredFileName);return NotFound();}TempData["FacultySuccess"]="Resource draft created.";return RedirectToAction(nameof(Details),new{id});}
    [HttpGet]public async Task<IActionResult> Edit(int id,CancellationToken token){var c=await Context(token);if(c is null)return Challenge();var x=await _service.GetOwnedAsync(c.Value.User.Id,id,token:token);if(x is null)return NotFound();if(x.Status==FacultyResourceStatus.Archived)return BadRequest();var m=Form(x);await Prepare(m,c.Value.User.Id,token);Shell(m,c.Value.User,c.Value.Profile);return View(m);}
    [HttpPost,ValidateAntiForgeryToken,RequestSizeLimit(ResourceService.MaximumFileSize+1_048_576)]public async Task<IActionResult> Edit(int id,FacultyResourceFormViewModel m,CancellationToken token){if(m.Id!=id)return BadRequest();var c=await Context(token);if(c is null)return Challenge();var current=await _service.GetOwnedAsync(c.Value.User.Id,id,token:token);if(current is null)return NotFound();m.CurrentStatus=current.Status;m.ExistingFileName=current.OriginalFileName;await Validate(m,true,current,token);StoredResourceFile? stored=null;if(ModelState.IsValid&&m.Kind==ResourceKind.File&&m.Upload is not null)try{await ValidateSignature(m.Upload,token);if(ModelState.IsValid)stored=await _files.StoreFileAsync(m.Upload,token);}catch(InvalidOperationException e){ModelState.AddModelError(nameof(m.Upload),e.Message);}if(!ModelState.IsValid){await Prepare(m,c.Value.User.Id,token);Shell(m,c.Value.User,c.Value.Profile);return View(m);}var old=current.StoredFileName;if(!await _service.UpdateAsync(c.Value.User.Id,id,Input(m),stored,token)){if(stored is not null)await _files.DeleteStoredFileAsync(stored.StoredFileName);return NotFound();}if(old is not null&&(stored is not null||m.Kind==ResourceKind.Link))await _files.DeleteStoredFileAsync(old);TempData["FacultySuccess"]="Resource updated.";return RedirectToAction(nameof(Details),new{id});}
    [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> Publish(int id,CancellationToken token){var uid=_users.GetUserId(User);if(uid is null)return Challenge();var r=await _service.PublishAsync(uid,id,token);TempData[r.Succeeded?"FacultySuccess":"FacultyError"]=r.Succeeded?$"Resource published to {r.StudentCount} matching student course(s).":r.Error;return RedirectToAction(nameof(Details),new{id});}
    [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> Archive(int id,CancellationToken token){var uid=_users.GetUserId(User);if(uid is null)return Challenge();if(!await _service.ArchiveAsync(uid,id,token))return NotFound();TempData["FacultySuccess"]="Resource archived.";return RedirectToAction(nameof(Details),new{id});}
    [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult> Delete(int id,CancellationToken token){var uid=_users.GetUserId(User);if(uid is null)return Challenge();var x=await _service.DeleteDraftAsync(uid,id,token);if(x is null)return BadRequest();await _files.DeleteStoredFileAsync(x.StoredFileName);TempData["FacultySuccess"]="Draft deleted.";return RedirectToAction(nameof(Index));}
    [HttpGet]public async Task<IActionResult> Download(int id,CancellationToken token){var uid=_users.GetUserId(User);if(uid is null)return Challenge();var x=await _service.GetOwnedAsync(uid,id,token:token);if(x?.StoredFileName is null)return NotFound();var stream=await _files.OpenFileAsync(x.StoredFileName,token);return stream is null?NotFound():File(stream,x.ContentType??"application/octet-stream",x.OriginalFileName??"resource");}
    [HttpGet]public async Task<IActionResult> OpenLink(int id,CancellationToken token){var uid=_users.GetUserId(User);if(uid is null)return Challenge();var x=await _service.GetOwnedAsync(uid,id,token:token);return x is null||!SafeUrl(x.ExternalUrl,out var url)?NotFound():Redirect(url);}
    private async Task Validate(FacultyResourceFormViewModel m,bool edit,FacultyResource? existing,CancellationToken token){if(m.Kind.HasValue&&!Enum.IsDefined(m.Kind.Value))ModelState.AddModelError(nameof(m.Kind),"Select a valid source.");if(m.Category.HasValue&&!Enum.IsDefined(m.Category.Value))ModelState.AddModelError(nameof(m.Category),"Select a valid category.");if(m.AssignmentId.HasValue&&!await _db.FacultyCourseAssignments.AnyAsync(x=>x.Id==m.AssignmentId&&x.IsActive&&x.FacultyProfile.ApplicationUserId==_users.GetUserId(User),token))ModelState.AddModelError(nameof(m.AssignmentId),"Select one of your assigned courses.");if(m.Kind==ResourceKind.File&&m.Upload is null&&!(edit&&existing?.StoredFileName is not null))ModelState.AddModelError(nameof(m.Upload),"Select a file.");if(m.Kind==ResourceKind.Link){if(!SafeUrl(m.ExternalUrl,out var url))ModelState.AddModelError(nameof(m.ExternalUrl),"Enter a valid HTTP or HTTPS URL.");else m.ExternalUrl=url;}}
    private static bool SafeUrl(string? value,out string url){url="";if(!Uri.TryCreate(value?.Trim(),UriKind.Absolute,out var u)||(u.Scheme!="http"&&u.Scheme!="https"))return false;url=u.AbsoluteUri;return true;}
    private static async Task ValidateSignature(IFormFile f,CancellationToken token){if(f.Length<=0||f.Length>ResourceService.MaximumFileSize)throw new InvalidOperationException("File must be between 1 byte and 20 MB.");var ext=Path.GetExtension(f.FileName).ToLowerInvariant();if(!ResourceService.AllowedExtensions.Contains(ext))throw new InvalidOperationException("This file type is not allowed.");await using var s=f.OpenReadStream();var b=new byte[Math.Min(16,(int)f.Length)];await s.ReadExactlyAsync(b.AsMemory(),token);bool ok=ext switch{".pdf"=>b.AsSpan().StartsWith("%PDF"u8),".png"=>b.Length>=8&&b.AsSpan(0,8).SequenceEqual(new byte[]{137,80,78,71,13,10,26,10}),".jpg" or ".jpeg"=>b.Length>=3&&b[0]==255&&b[1]==216&&b[2]==255,".gif"=>b.AsSpan().StartsWith("GIF8"u8),".webp"=>b.Length>=12&&b.AsSpan(0,4).SequenceEqual("RIFF"u8)&&b.AsSpan(8,4).SequenceEqual("WEBP"u8),".zip" or ".docx" or ".pptx" or ".xlsx"=>b.Length>=4&&b[0]==80&&b[1]==75,".doc" or ".ppt" or ".xls"=>b.Length>=8&&b.AsSpan(0,8).SequenceEqual(new byte[]{208,207,17,224,161,177,26,225}),_=>!b.Contains((byte)0)};if(!ok)throw new InvalidOperationException("File content does not match its extension.");}
    private async Task Prepare(FacultyResourceFormViewModel m,string uid,CancellationToken token)=>m.Courses=await _courses.GetCourseOptionsAsync(uid,token);private static FacultyResourceInput Input(FacultyResourceFormViewModel m)=>new(m.AssignmentId!.Value,m.Title,m.Description,m.Kind!.Value,m.Category!.Value,m.Tags,m.ExternalUrl);private static FacultyResourceFormViewModel Form(FacultyResource x)=>new(){Id=x.Id,AssignmentId=x.FacultyCourseAssignmentId,Title=x.Title,Description=x.Description,Kind=x.Kind,Category=x.Category,Tags=x.Tags,ExternalUrl=x.ExternalUrl,ExistingFileName=x.OriginalFileName,CurrentStatus=x.Status};
    private async Task<(ApplicationUser User,FacultyProfile Profile)?> Context(CancellationToken token){var u=await _users.GetUserAsync(User);if(u is null)return null;var p=await _db.FacultyProfiles.AsNoTracking().Include(x=>x.Department).SingleOrDefaultAsync(x=>x.ApplicationUserId==u.Id,token);return p is null?null:(u,p);}private static void Shell(FacultyShellViewModel m,ApplicationUser u,FacultyProfile p){var n=string.IsNullOrWhiteSpace(u.FullName)?u.Email??"Faculty":u.FullName;var parts=n.Split(' ',StringSplitOptions.RemoveEmptyEntries);m.FullName=n;m.Email=u.Email??"";m.FacultyId=p.FacultyId;m.DepartmentLabel=p.Department?.Name??"Department not assigned";m.DesignationLabel=p.Designation??"Faculty member";m.HasProfileImage=p.ProfileImageData is not null;m.ProfileImageVersion=(p.UpdatedAt??p.CreatedAt).ToUnixTimeSeconds();m.Initials=parts.Length>1?$"{parts[0][0]}{parts[^1][0]}".ToUpperInvariant():n[..Math.Min(2,n.Length)].ToUpperInvariant();}private static string? CleanSearch(string? s)=>string.IsNullOrWhiteSpace(s)?null:s.Trim()[..Math.Min(100,s.Trim().Length)];
}
